server.port: 8080

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
solon:
  # ...
  dataSources:
    ds1!: # 数据源-ds1
      class: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/sadmin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root

easy-query:
  ds1:  # 数据源-ds1
    database: mysql # 数据库类型设置为mysql
    print-sql: true # 打印SQL日志
    update-strategy: only_not_null_columns # 更新策略，只更新NOT NULL的字段

redis:
  rd1: # 数据源-ds1
    server: localhost:6379  # Redis服务地址
    db: 1 # Redis数据库编号

sa-token:
  token-name: authtoken # Token名称
  timeout: 2592000  # Token有效期
  is-concurrent: false # 是否允许同一账号并发登录
  token-style: uuid # Token风格
  is-log: true # 打印日志